export enum EngravingEnum {
    MassIncrease="MassIncrease",
    KeenBluntWeapon="KeenBluntWeapon",
    CurseDoll ="CurseDoll",
    Mayhem = "Mayhem",
    RaidCaptain="RaidCaptain",
    SpiritAbsorption="SpiritAbsorption",
    HeavyArmor="HeavyArmor",
    Adrenaline="Adrenaline",
    AmbushMaster="AmbushMaster",
    MpEfficiencyIncrease="MpEfficiencyIncrease",
    TrueCourage="TrueCourage",
    Contender="Contender",
    PreemptiveStrike="PreemptiveStrike",
    Grudge="Grudge",
    MasterEscape="MasterEscape",
    EtherPredator="EtherPredator",
    DesperateSalvation="DesperateSalvation",
    PreciseDagger="PreciseDagger",
    AllOutAttack="AllOutAttack",
    HitMaster="HitMaster",
    SightFocus="SightFocus",
    MasterTenacity="MasterTenacity",
    Others="Others"
}
